"""Why each thing happened. Deterministic rules only.

Every sentence here is derived from something the system actually knows: a
tool's classification in the live registry, a relevance reason recorded when a
memory was selected, the evidence a verification gathered. None is generated by
a model, which is the property that makes "why did you do that?" answerable
rather than merely plausible-sounding.

Where a reason genuinely is not knowable, these functions say so rather than
composing something that reads well.
"""

from __future__ import annotations

from typing import Any

from app.tools.permissions import PermissionLevel

# --- approval ---------------------------------------------------------------

_PERMISSION_REASON = {
    PermissionLevel.CONFIRM: (
        "'{tool}' is classified CONFIRM in the live tool registry, so it stops "
        "for your decision before it can run."
    ),
    PermissionLevel.RESTRICTED: (
        "'{tool}' is classified RESTRICTED and cannot be run at all."
    ),
    PermissionLevel.SAFE: (
        "'{tool}' is classified SAFE — read-only, so it runs without asking."
    ),
}


def why_permission(tool: str, permission: str) -> str:
    """Why a tool did or did not need approval."""
    try:
        level = PermissionLevel(str(permission).upper())
    except ValueError:
        return f"'{tool}' has no known classification, so it was refused."
    return _PERMISSION_REASON[level].format(tool=tool)


def why_tool(tool: str, definition: Any | None) -> str:
    """What a tool is for, from its own declared purpose or description.

    Read from the live registry rather than a table here, so a new MCP server's
    tools explain themselves without a frontend change.
    """
    if definition is None:
        return f"'{tool}' is not in the current tool registry."
    purpose = (getattr(definition, "meta", None) or {}).get("purpose")
    if purpose:
        return str(purpose)
    description = (getattr(definition, "description", "") or "").strip()
    if description:
        # The first sentence is the tool's own summary; the rest is written for
        # the model and reads poorly to a person.
        return description.split(". ")[0].rstrip(".") + "."
    return f"'{tool}' does not describe itself."


# --- context ----------------------------------------------------------------


def why_memory(memory: Any) -> str:
    """Why a memory was selected, from the relevance reasons recorded when it
    was scored (Phase 10). Never invented after the fact."""
    reasons = tuple(getattr(memory, "reasons", ()) or ())
    if reasons:
        return "Selected because " + "; ".join(reasons) + "."
    return "Selected as one of the most recently updated memories."


def why_workspace(workspace: Any) -> str:
    if getattr(workspace, "active", False):
        return (
            "Treated as the active workspace: it was the first observed "
            "candidate that verified on disk."
        )
    return "Checked as a candidate workspace but not treated as the active one."


def why_observation() -> str:
    return "Included because the request asked about what has recently happened."


# --- outcome ----------------------------------------------------------------

_OUTCOME_FALLBACK = {
    "SUCCESS": "The evidence gathered confirmed the intended result.",
    "PARTIAL_SUCCESS": "The action completed, but only part of it could be confirmed.",
    "FAILED": "The evidence showed the intended result did not happen.",
    "UNKNOWN": (
        "The action completed, but there was not enough evidence to establish "
        "whether it achieved what was asked."
    ),
}


def why_outcome(outcome: str, evidence: list[str], unknowns: list[str]) -> str:
    """Why the outcome is what it is, built from the evidence itself.

    Deliberately not the verification's own summary — that sentence is written
    for the model. This one names the facts, because "SUCCESS because X and Y"
    is the thing a person wants when they ask why.
    """
    outcome = str(outcome).upper()
    observed = [e for e in evidence if e]

    if observed:
        joined = " and ".join(observed[:3])
        if outcome == "SUCCESS":
            return f"SUCCESS because {joined}."
        if outcome == "FAILED":
            return f"FAILED because {joined}."
        if outcome == "PARTIAL_SUCCESS":
            missing = f" What could not be confirmed: {unknowns[0]}." if unknowns else ""
            return f"Partly confirmed: {joined}.{missing}"

    if outcome == "UNKNOWN" and unknowns:
        return f"Not verified: {unknowns[0]}."
    return _OUTCOME_FALLBACK.get(outcome, "The outcome could not be established.")


# --- the one-line summary ---------------------------------------------------


def summarise(
    *,
    tools_run: list[str],
    approved: int,
    denied: int,
    outcome: str | None,
    context_kinds: list[str],
    cancelled: bool = False,
) -> str:
    """One plain sentence describing what the request actually did.

    Assembled from counts and names — there is no path by which this can claim
    something that did not happen, because it has nothing to draw on but the
    steps themselves.
    """
    if cancelled:
        return "The request was cancelled before it finished."

    parts: list[str] = []
    if context_kinds:
        parts.append("Gathered " + ", ".join(context_kinds[:3]))

    if tools_run:
        named = ", ".join(dict.fromkeys(tools_run[:3]))
        if approved:
            parts.append(f"ran {named} after you approved it")
        else:
            parts.append(f"ran {named}")
    elif denied:
        parts.append("stopped because you declined the action")
    elif not context_kinds:
        return "Answered without needing any tools."

    # The outcome clause is joined with its own conjunction rather than the
    # "then" used between actions, so the sentence reads as one clause.
    tail = {
        "SUCCESS": " and verified the result",
        "FAILED": " and found it did not work",
        "PARTIAL_SUCCESS": " and partly confirmed the result",
        "UNKNOWN": ", but could not verify the result",
    }.get(outcome or "", "")

    sentence = ", then ".join(parts) if len(parts) > 1 else (parts[0] if parts else "")
    if not sentence:
        return "Nothing to report."
    sentence += tail
    return sentence[:1].upper() + sentence[1:] + "."


__all__ = [
    "summarise",
    "why_memory",
    "why_observation",
    "why_outcome",
    "why_permission",
    "why_tool",
    "why_workspace",
]
