"""How NEXUS reached a result.

Read-only, and derived entirely from events that already fired. There are
deliberately no mutation routes here — no execute, no retry, no approve —
because a trace is a view of the past, and giving it a verb would make it a
second execution path with none of the existing checks.
"""

from __future__ import annotations

from fastapi import APIRouter, HTTPException, status

from app.api.deps import RunnerDep
from app.api.schemas import ErrorResponse, TraceResponse

router = APIRouter(prefix="/api/tasks", tags=["trace"])


@router.get(
    "/{task_id}/trace",
    response_model=TraceResponse,
    summary="How NEXUS reached this result",
    description=(
        "The execution trace for one task: what context was gathered, which "
        "tools were requested, what you approved, what was verified, and the "
        "evidence behind the outcome. Projected from the events that actually "
        "fired — never reconstructed, and never generated by a model."
    ),
    responses={404: {"model": ErrorResponse, "description": "Unknown task"}},
)
async def get_trace(task_id: str, runner: RunnerDep) -> TraceResponse:
    trace = await runner.trace_for(task_id)
    if trace is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"No trace is available for task '{task_id}'.",
        )
    return TraceResponse.model_validate(trace.to_public_dict())
